### Uses rest_sample.rds generated by sampling_rest.R

library(yelpr)
library(dplyr)

seed <- 3234

key <- readLines("api_key.txt")
rest_sample <- readRDS(paste0("rest_sample_", seed, ".rds"))
radius = 16000 # about 10 miles
plot(st_geometrycollection(rest_sample))
# this plot shows that the sample is biased towards to the places where border
# is not smooth. On these places the border is longer and gets more weigth 
# for sampling but it covers a small area.

# Create a list of dataframes. Because each cluster (a 
# group of business centered around a border point) will
# be used to generate the variables within itself.

data_list <- list()
z <- 1
for(i in rest_sample){
  longitude <- i[1]
  latitude <- i[2]
  cat("\r", z, " ", latitude, " ", longitude)
  # https://www.yelp.com/developers/documentation/v3/business_search
  bus_data <- suppressMessages(business_search(
    api_key = key,
    latitude = latitude,
    longitude = longitude,
    radius = radius,
    # open_now = TRUE, # don't use this. Now means this time of the day.
    # Instead, see the is_closed in the data returned.
    limit = 50 # Using the offset and limit parameters, you can get up to 1000
    # businesses from this endpoint if there are more than 1000 results.
  ))
  z <- z + 1
  if(is.null(bus_data$total)) next()
  if(bus_data$total == 0) next()
  bus_data <- bus_data$businesses
  bus_data <- cbind(bus_data %>% select(-c(coordinates, location)),
                    (bus_data %>% select(coordinates))[[1]],
                    (bus_data %>% select(location))[[1]])
  bus_data <- bus_data %>% select(-c(alias, image_url, url, categories,
                                     transactions, address1, address2,
                                     address3, country, display_address,
                                     phone, display_phone))
  data_list[[paste(latitude, longitude, sep = ",")]] <- bus_data
}
saveRDS(data_list,paste0("rest_data_", seed, ".rds"))


