library(dplyr)
library(sf)

# rest_data contains a list of restaurant clusters around 
# a border point. It is generated by collect_rest_data.R
rest_data <- readRDS("rest_data.rds")
rest_data[[1]]

cluster <- rest_data[[1]]
states <- data.frame(table(cluster$state))
names(states) <- c("State", "Count")
# make the state with most rest your focal state
focal <- as.character(states[which.max(states$Count), "State"])
cluster$is_focal <- cluster$state == focal
