library(dplyr)
library(sf)
library(stringr)
seed <- 8234


# rest_data contains a list of restaurant clusters around 
# a border point. It is generated by collect_rest_data.R
rest_data <- list()
for(i in seq(1234, seed, 1000)){
  rest_data <- c(rest_data, readRDS(paste0("rest_data_", seed, ".rds")))
}

rest_data[[1]]

# drop the clusters with less than 2 states
meets_requirement <- function(cluster){
  has_price <- !is.na(cluster$price) 
  cluster <- cluster[has_price, ]
  states <- length(unique(cluster$state))
  return(states > 1)
}

keep_cluster <- sapply(rest_data, meets_requirement)
rest_data <- rest_data[keep_cluster]

# read tax data
tax_rates <- do.call(rbind,
                     lapply(list.files(path = "./TAXRATES_ZIP5",
                                       pattern = "*.csv",
                                       full.names = T),
                            read.csv, header = T,
                            colClasses = c(ZipCode = "character"))) 
names(tax_rates) <- str_remove(names(tax_rates), "Estimated")
tax_rates <- tax_rates[, c("ZipCode", "StateRate", "CountyRate", "CityRate",
                           "SpecialRate", "CombinedRate")]

raw_data <- data.frame()
reg_data <- data.frame()
for(i in 1:length(rest_data)){
  cluster <- rest_data[[i]]
  cluster <- cluster[complete.cases(cluster[,c("price", "state")]) , ]
  price_dic <- 1:4
  names(price_dic) <- c("$", "$$", "$$$", "$$$$")
  cluster$price <- price_dic[cluster$price]
  # merge with taxes
  cluster <- merge(cluster, tax_rates, by.x = "zip_code", "ZipCode",
                   all.x = T)
  # randomly make one of the states focal 
  states <- unique(cluster$state)
  cluster$is_focal <- cluster$state == sample(states, 1)
  
  cluster$cluster <- names(rest_data)[i]
  raw_data <- rbind(raw_data, cluster)
  
  # split the data and make both sf objects
  focal <- st_as_sf(cluster[cluster$is_focal == T, ],
                    coords = c("longitude", "latitude"))
  nonfocal <- st_as_sf(cluster[cluster$is_focal == F, ],
                       coords = c("longitude", "latitude"))
  st_crs(focal) <- 4326
  st_crs(nonfocal) <- 4326
  proxy_mat <- 1 / st_distance(focal, nonfocal) # rows: Focal, columns: nonFocal
  dimnames(proxy_mat) <- list(focal$id, nonfocal$id)
  proxy_mat <- proxy_mat / rowSums(proxy_mat, na.rm = T)
  # Subset dataframes and convert to matrix
  st_geometry(focal) <- NULL
  focal_mat <- as.matrix(focal[, c("review_count", "rating", "price", "StateRate",
                                   "CountyRate", "CityRate", "SpecialRate",
                                   "CombinedRate")])
  rownames(focal_mat) <- focal$id
  st_geometry(nonfocal) <- NULL
  nonfocal_mat <- as.matrix(nonfocal[, c("review_count", "rating", "price", "StateRate",
                                         "CountyRate", "CityRate", "SpecialRate",
                                         "CombinedRate")])
  rownames(nonfocal_mat) <- nonfocal$id
  # demean the variables
  focal_mat <- focal_mat - proxy_mat %*% nonfocal_mat
  focal_mat <- data.frame(focal_mat)
  focal_mat$cluster <- names(rest_data)[i]
  focal_mat$id <- focal$id
  reg_data <- rbind(reg_data, focal_mat)
}
write.csv(raw_data, "raw_data.csv")
summary(reg_data)
cor(reg_data[complete.cases(reg_data), sapply(reg_data, is.numeric)])
head(reg_data)
write.csv(reg_data, "reg_data.csv")


{
  # get_stats <- function(x){
  #   n_obs <-  nrow(x)
  #   has_price <- !is.na(x$price)
  #   n_has_price <- sum(has_price)
  #   # do not include rests without price to into stats
  #   x <- x[has_price, ]
  #   if(nrow(x) == 0) return(c(n_obs, n_has_price, rep(NA, 3))) # change 5 to the return's length if needed
  #   states <- data.frame(table(x$state))
  #   names(states) <- c("State", "Count")
  #   n_states <- nrow(states)
  #   # make the state with most rest your focal state
  #   focal <- as.character(states[which.max(states$Count), "State"])
  #   x$is_focal <- x$state == focal
  #   n_focal <- sum(x$is_focal)
  #   n_nonfocal <- sum(!x$is_focal)
  #   return(c(n_obs, n_has_price, n_states, n_focal, n_nonfocal))
  # }
  # cluster_stats <- sapply(rest_data, get_stats)
  # cluster_stats <- t(cluster_stats)
  # colnames(cluster_stats) <- c("n_obs", "n_has_price", "n_states", "n_focal",
  #                              "n_nonfocal")
  # apply(cluster_stats, 2, summary)
  # n_nonfocal_count <- table(cluster_stats[, "n_nonfocal"])
  # n_nonfocal <- as.numeric(names(n_nonfocal_count))
  # n_nonfocal_count[n_nonfocal >= 5] %>% sum()


# # subset the clusters with at least 5 restaurants in the second state with most
# has_5 <- cluster_stats[, "n_nonfocal"] >= 5
# has_5 <- ifelse(is.na(has_5), F, has_5)
# data_list <- rest_data[has_5]
# subset_stats <- sapply(data_list, get_stats)
# subset_stats <- t(subset_stats)
# colnames(subset_stats) <- c("n_obs", "n_has_price", "n_states", "n_focal",
#                             "n_nonfocal")
# apply(subset_stats, 2, summary)
# sum(subset_stats[, "n_focal"]) # number of observations to be used in the analysis
}